/* ═══════════════════════════════════════════════════════════════
   Ocean Fast Ferries · Baggage Pro V300 — Live Map Module (V126)
   ═══════════════════════════════════════════════════════════════ */

(function(){
  'use strict';
  var VERSION='V500 Live Map Pro Weather Ops';
  var DELAY_KEY='oj_v500_map_delays';
  var FILTER_KEY='oj_v500_map_filter';
  var selectedId=null, activeFilter=localStorage.getItem(FILTER_KEY)||'cebu_departures';
  var map=null, refreshTimer=null, layers={markers:[],routes:[],ports:[],labels:[],weather:[]}
  var weatherCache=null, weatherLastFetch=0;
  var tripCache=[];
  var PORTS={
    cebu:[10.2945,123.9056], tagbilaran:[9.6496,123.8547], getafe:[10.1491,124.1586], ormoc:[11.0064,124.6075],
    palompon:[11.0500,124.3840], maasin:[10.1336,124.8440], surigao:[9.7843,125.4888], siquijor:[9.2142,123.5150],
    dumaguete:[9.3068,123.3054], bacolod:[10.6765,122.9509], iloilo:[10.7202,122.5621], calapan:[13.4117,121.1803], batangas:[13.7565,121.0583]
  };
  var ROUTE_WAYPOINTS={
    cebu_dumaguete:['cebu','tagbilaran','dumaguete'], cebu_siquijor:['cebu','tagbilaran','siquijor'], cebu_surigao:['cebu','maasin','surigao'],
    dumaguete_cebu:['dumaguete','tagbilaran','cebu'], siquijor_cebu:['siquijor','tagbilaran','cebu'], surigao_cebu:['surigao','maasin','cebu']
  };
  function id(x){return document.getElementById(x)}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function db(){try{return DB||{}}catch(e){return window.DB||{}}}
  function toastMsg(s){try{toast(s)}catch(e){console.log(s)}}
  function download(name,content,type){var blob=content instanceof Blob?content:new Blob([content],{type:type||'text/plain'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},400)}
  function csv(rows){return rows.map(function(r){return r.map(function(v){v=String(v==null?'':v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}).join(',')}).join('\n')}
  function cap(s){return String(s||'').replace(/_/g,' ').replace(/\b\w/g,function(m){return m.toUpperCase()})}
  function routePorts(key){var p=String(key||'').split('_');return {from:p[0]||'',to:p[1]||''}}
  function pathFor(key){var names=ROUTE_WAYPOINTS[key]||[routePorts(key).from,routePorts(key).to];return names.map(function(n){return PORTS[n]}).filter(Boolean)}
  function dist(a,b){var R=6371,dLat=(b[0]-a[0])*Math.PI/180,dLon=(b[1]-a[1])*Math.PI/180,la1=a[0]*Math.PI/180,la2=b[0]*Math.PI/180;var h=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)*Math.sin(dLon/2);return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
  function pointAt(path,pct){if(!path.length)return [10.2945,123.9056];if(path.length===1)return path[0];pct=Math.max(0,Math.min(1,pct));var segs=[],total=0;for(var i=0;i<path.length-1;i++){var d=dist(path[i],path[i+1]);segs.push(d);total+=d}var target=total*pct,run=0;for(var j=0;j<segs.length;j++){if(target<=run+segs[j]||j===segs.length-1){var r=segs[j]?((target-run)/segs[j]):0,a=path[j],b=path[j+1];return [a[0]+(b[0]-a[0])*r,a[1]+(b[1]-a[1])*r]}run+=segs[j]}return path[path.length-1]}
  function bearing(a,b){var y=Math.sin((b[1]-a[1])*Math.PI/180)*Math.cos(b[0]*Math.PI/180);var x=Math.cos(a[0]*Math.PI/180)*Math.sin(b[0]*Math.PI/180)-Math.sin(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.cos((b[1]-a[1])*Math.PI/180);return (Math.atan2(y,x)*180/Math.PI+360)%360}
  function parseTime(str,base){var s=String(str||'').trim();var m=s.match(/(\d{1,2})\s*:\s*(\d{2})\s*([AaPp][Mm])?/);if(!m)return new Date(base);var h=parseInt(m[1],10),min=parseInt(m[2],10),ap=m[3]?m[3].toLowerCase():'';if(ap==='pm'&&h<12)h+=12;if(ap==='am'&&h===12)h=0;var d=new Date(base);d.setHours(h,min,0,0);return d}
  function fmtTime(d){return d?d.toLocaleTimeString('en-PH',{hour:'numeric',minute:'2-digit',hour12:true}):'--'}
  function mins(n){return Math.round(n/60000)}
  function delayMap(){try{return JSON.parse(localStorage.getItem(DELAY_KEY)||'{}')}catch(e){return {}}}
  function saveDelays(x){localStorage.setItem(DELAY_KEY,JSON.stringify(x||{}))}
  function statusFor(t,now){var d=t.actualDep,a=t.actualArr,delta=mins(d-now),afterDep=mins(now-d),afterArr=mins(now-a);var delayed=t.delay>0&&now<a;if(now<d){if(delta<=15)return {text:delayed?'Delayed Boarding':'Boarding Now',cls:delayed?'delayed':'boarding'};if(delta<=45)return {text:delayed?'Delayed Soon':'Boarding Soon',cls:delayed?'delayed':'soon'};return {text:delayed?'Delayed':'Scheduled',cls:delayed?'delayed':'scheduled'}}if(now>=d&&now<a)return {text:delayed?'En Route Delayed':'En Route',cls:delayed?'delayed':'enroute'};if(afterArr<=60)return {text:'Arrived',cls:'arrived'};return {text:'Completed',cls:'completed'}}
  function progressFor(t,now){var total=t.actualArr-t.actualDep;if(total<=0)return 1;return Math.max(0,Math.min(1,(now-t.actualDep)/total))}
  function makeTrips(){var D=db(),schedules=D.schedules||{},delays=delayMap(),now=new Date(),today=new Date();today.setHours(0,0,0,0);var out=[];Object.keys(schedules).forEach(function(key){var sc=schedules[key]||{},path=pathFor(key);if(!path.length||!Array.isArray(sc.trips))return;sc.trips.forEach(function(row,idx){[0,1].forEach(function(dayOffset){var base=new Date(today);base.setDate(today.getDate()+dayOffset);var dep=parseTime(row.dep,base),arr=parseTime(row.arr||row.dep,base);if(arr<=dep)arr.setDate(arr.getDate()+1);var rawId=key+'_'+idx+'_'+dayOffset+'_'+String(row.dep).replace(/\W/g,'')+'_'+String(row.vessel||'v').replace(/\W/g,'');var delay=Number(delays[rawId]||0)||0;var actualDep=new Date(dep.getTime()+delay*60000),actualArr=new Date(arr.getTime()+delay*60000);var st=statusFor({actualDep:actualDep,actualArr:actualArr,delay:delay},now),progress=progressFor({actualDep:actualDep,actualArr:actualArr},now);var ports=routePorts(key),pos=pointAt(path,progress);var nextPoint=pointAt(path,Math.min(1,progress+.02));out.push({id:rawId,key:key,index:idx,dayOffset:dayOffset,title:sc.title||cap(key),travel:sc.travel||'',dep:row.dep||'',arr:row.arr||'',vessel:row.vessel||'Vessel',remarks:row.remarks||'',scheduledDep:dep,scheduledArr:arr,actualDep:actualDep,actualArr:actualArr,delay:delay,status:st.text,cls:st.cls,progress:progress,progressPct:Math.round(progress*100),origin:ports.from,dest:ports.to,path:path,pos:pos,bearing:bearing(pos,nextPoint),etaMin:Math.max(0,mins(actualArr-now)),toDepMin:mins(actualDep-now),recent:(now>=actualDep&&mins(now-actualDep)<=60),isCebuDep:ports.from==='cebu',isCebuArr:ports.to==='cebu',isConnecting:!!ROUTE_WAYPOINTS[key]})})})});out.sort(function(a,b){return a.actualDep-b.actualDep});tripCache=out;return out}
  function todaysTrips(){var today=new Date().toDateString();return makeTrips().filter(function(t){return t.scheduledDep.toDateString()===today||t.status==='En Route'||t.recent})}
  function nextBoarding(){var now=new Date();return makeTrips().filter(function(t){return t.isCebuDep&&t.actualDep>=new Date(now.getTime()-5*60000)}).sort(function(a,b){return a.actualDep-b.actualDep})[0]||null}
  function recentlyDeparted(){var now=new Date();return makeTrips().filter(function(t){return t.isCebuDep&&now>=t.actualDep&&mins(now-t.actualDep)<=60}).sort(function(a,b){return b.actualDep-a.actualDep})}
  function filteredTrips(){var q=(id('oj126Search')?id('oj126Search').value:'').toLowerCase().trim();var list=todaysTrips();if(activeFilter==='cebu_departures')list=list.filter(function(t){return t.isCebuDep});else if(activeFilter==='cebu_arrivals')list=list.filter(function(t){return t.isCebuArr});else if(activeFilter==='enroute')list=list.filter(function(t){return t.cls==='enroute'||t.status.indexOf('En Route')>=0});else if(activeFilter==='recent')list=list.filter(function(t){return t.recent});if(q)list=list.filter(function(t){return (t.vessel+' '+t.title+' '+t.dep+' '+t.arr+' '+t.key+' '+t.status).toLowerCase().indexOf(q)>=0});return list.sort(function(a,b){return a.actualDep-b.actualDep})}
  function fareSummary(t){var fares=(db().paxFares||{})[t.key];if(!fares)return 'Fare: not set';return 'TC/OA ₱'+Number(fares['TC/OA']||0).toLocaleString('en-PH')+' • BC ₱'+Number(fares.BC||0).toLocaleString('en-PH')}
  function statusPill(t){return '<span class="oj126-pill '+esc(t.cls)+'">● '+esc(t.status)+'</span>'}
  function tripLine(t){return esc(t.vessel)+' • '+esc(t.title)+' • '+fmtTime(t.actualDep)+' → '+fmtTime(t.actualArr)+' • '+t.progressPct+'%'}
  function renderTop(){var n=nextBoarding(),recent=recentlyDeparted();var en=todaysTrips().filter(function(t){return t.cls==='enroute'||t.status.indexOf('En Route')>=0}).length;var html='';if(n){var label=n.toDepMin>0?'Boarding in '+n.toDepMin+' min':(n.toDepMin>=-5?'Boarding / Departing now':'Departed');html+='<div class="oj126-hero"><div class="oj126-title"><span>🚢 Next Boarding from Cebu</span><span class="oj126-badge">Schedule-Based</span></div><div class="oj126-sub">'+esc(n.vessel)+' — '+esc(n.title)+'</div><div class="oj126-grid" style="margin-top:10px"><div class="oj126-stat"><b>'+esc(label)+'</b><span>Depart '+fmtTime(n.actualDep)+' · Arrive '+fmtTime(n.actualArr)+'</span></div><div class="oj126-stat"><b>'+statusPill(n)+'</b><span>'+fareSummary(n)+'</span></div></div><div class="oj126-progress"><i style="width:'+n.progressPct+'%"></i></div><div class="oj126-actions"><button class="primary sm" onclick="OJLiveMapV126.select(\''+esc(n.id)+'\')">Open Details</button><button class="sm" onclick="OJLiveMapV126.focusNext()">Focus on Map</button><button class="sm" onclick="OJLiveMapV126.ask(\''+esc(n.id)+'\')">Ask Gemini</button></div></div>'}else{html+='<div class="oj126-hero"><div class="oj126-title"><span>🚢 Next Boarding from Cebu</span><span class="oj126-badge">No upcoming Cebu departure found today</span></div><div class="oj126-sub">Try All Routes or check tomorrow\'s schedule.</div></div>'}
    html+='<div class="oj126-grid"><div class="oj126-card"><div class="oj126-title"><span>🕘 Recently Departed</span><span class="oj126-badge">Past 60 min</span></div><div class="oj126-list" style="margin-top:10px">'+(recent.length?recent.slice(0,5).map(function(t){return '<div class="oj126-item" onclick="OJLiveMapV126.select(\''+esc(t.id)+'\')"><b>'+esc(t.vessel)+'</b> '+statusPill(t)+'<br><span class="oj126-small">'+esc(t.title)+' departed '+mins(new Date()-t.actualDep)+' min ago · '+t.progressPct+'%</span><div class="oj126-progress"><i style="width:'+t.progressPct+'%"></i></div></div>'}).join(''):'<div class="oj126-note">No Cebu vessel departed in the last 60 minutes.</div>')+'</div></div><div class="oj126-card"><div class="oj126-title"><span>📡 Map Ops Counters</span><span class="oj126-badge">Today</span></div><div class="oj126-grid" style="margin-top:10px"><div class="oj126-stat"><b>'+todaysTrips().filter(function(t){return t.isCebuDep}).length+'</b><span>Cebu departures</span></div><div class="oj126-stat"><b>'+en+'</b><span>En route now</span></div><div class="oj126-stat"><b>'+recent.length+'</b><span>Recent departures</span></div><div class="oj126-stat"><b>'+todaysTrips().filter(function(t){return t.delay>0}).length+'</b><span>Manual delays</span></div></div></div></div>';return html}
  function filtersHtml(){var filters=[['cebu_departures','Cebu departures'],['cebu_arrivals','Cebu arrivals'],['enroute','En route now'],['recent','Recently departed'],['all','All routes']];return '<div class="oj126-card"><div class="oj126-title"><span>🎛️ Accurate Map Filters</span><span class="oj126-badge">No fake GPS</span></div><div class="oj126-controls" style="margin-top:10px">'+filters.map(function(f){return '<button class="sm '+(activeFilter===f[0]?'primary':'')+'" onclick="OJLiveMapV126.setFilter(\''+f[0]+'\')">'+f[1]+'</button>'}).join('')+'</div><div class="oj126-searchrow" style="margin-top:10px"><input id="oj126Search" placeholder="Search vessel, route, time, status..." oninput="OJLiveMapV126.refresh()"><button class="sm" onclick="OJLiveMapV126.focusCebu()">Focus Cebu Port</button></div><div class="oj126-note" style="margin-top:8px">Vessel positions are estimated from your schedule departure and arrival times. For true GPS accuracy, connect a vessel GPS/AIS or dispatch API later.</div></div>'}
  function delayHtml(){var list=makeTrips().filter(function(t){return t.isCebuDep||t.isCebuArr}).slice(0,30);return '<div class="oj126-card"><div class="oj126-title"><span>⏱️ Manual Delay Adjustment</span><span class="oj126-badge">Operational override</span></div><div class="oj126-delay" style="margin-top:10px"><select id="oj126DelayTrip">'+list.map(function(t){return '<option value="'+esc(t.id)+'">'+esc(t.vessel+' • '+t.title+' • '+fmtTime(t.scheduledDep))+(t.delay?' • +'+t.delay+'m':'')+'</option>'}).join('')+'</select><input id="oj126DelayMin" type="number" min="0" max="240" step="5" value="0"><button class="primary sm" onclick="OJLiveMapV126.applyDelay()">Apply</button></div><div class="oj126-actions"><button class="sm" onclick="OJLiveMapV126.resetDelays()">Reset all delays</button><button class="sm" onclick="OJLiveMapV126.exportCSV()">Export Vessel Manifest CSV</button></div></div>'}
  function detailHtml(t){if(!t){t=nextBoarding()||filteredTrips()[0]}if(!t)return '<div class="oj126-card oj126-detail"><div class="oj126-title">🧭 Vessel Intelligence</div><div class="oj126-note">Select a vessel to view details.</div></div>';selectedId=t.id;return '<div class="oj126-card oj126-detail"><div class="oj126-title"><span>🧭 Vessel Intelligence</span>'+statusPill(t)+'</div><div class="oj126-sub">'+esc(t.vessel)+' — '+esc(t.title)+'</div><div class="oj126-row"><span>Departure</span><b>'+fmtTime(t.actualDep)+(t.delay?' (+ '+t.delay+'m delay)':'')+'</b></div><div class="oj126-row"><span>Arrival / ETA</span><b>'+fmtTime(t.actualArr)+' / '+(t.etaMin?t.etaMin+' min':'Arrived')+'</b></div><div class="oj126-row"><span>Progress</span><b>'+t.progressPct+'%</b></div><div class="oj126-progress"><i style="width:'+t.progressPct+'%"></i></div><div class="oj126-row"><span>Travel time</span><b>'+esc(t.travel||'--')+'</b></div><div class="oj126-row"><span>Fare</span><b>'+esc(fareSummary(t))+'</b></div><div class="oj126-row"><span>Connection note</span><b>'+esc(t.isConnecting?'Connecting route / via port':'Direct route record')+'</b></div><div class="oj126-actions"><button class="primary sm" onclick="OJLiveMapV126.focus(\''+esc(t.id)+'\')">Focus Vessel</button><button class="sm" onclick="OJLiveMapV126.copy(\''+esc(t.id)+'\')">Copy Summary</button><button class="sm" onclick="OJLiveMapV126.ask(\''+esc(t.id)+'\')">Ask Gemini</button></div></div>'}
  function timelineHtml(){var list=filteredTrips().slice(0,12);return '<div class="oj126-card"><div class="oj126-title"><span>🧾 Route Timeline</span><span class="oj126-badge">'+list.length+' visible</span></div><div class="oj126-timeline" style="margin-top:10px">'+(list.length?list.map(function(t){return '<div class="oj126-timeitem" onclick="OJLiveMapV126.select(\''+esc(t.id)+'\')"><div class="time">'+fmtTime(t.actualDep)+'</div><div class="body"><b>'+esc(t.vessel)+'</b> '+statusPill(t)+'<br><small>'+esc(t.title)+' · ETA '+(t.etaMin?t.etaMin+'m':'--')+' · '+t.progressPct+'%</small><div class="oj126-progress"><i style="width:'+t.progressPct+'%"></i></div></div></div>'}).join(''):'<div class="oj126-note">No trips match this filter.</div>')+'</div></div>'}
  function mapHtml(){return '<div class="oj126-card"><div class="oj126-title"><span>🗺️ Live Map Pro Accurate Ops</span><span class="oj126-badge">Estimated Position + Weather</span></div><div class="oj126-mapbox" style="margin-top:10px"><div id="oj126LiveMap"></div></div><div class="oj126-note" style="margin-top:8px">Icons move according to scheduled departure/arrival time and manual delay overrides. This is not GPS-live.</div></div>'}
  function renderAll(){var container=id('oj126Top');if(container)container.innerHTML=renderTop();var detail=id('oj126Detail');if(detail)detail.innerHTML=detailHtml(tripCache.filter(function(t){return t.id===selectedId})[0]);var timeline=id('oj126Timeline');if(timeline)timeline.innerHTML=timelineHtml();if(id('oj126DelayTrip')){var old=id('oj126DelayTrip').value;var holder=id('oj126DelayHolder');if(holder)holder.innerHTML=delayHtml();if(id('oj126DelayTrip')&&old)id('oj126DelayTrip').value=old}renderMapLayers()}
  function clearLayers(){if(!map)return;Object.keys(layers).forEach(function(k){layers[k].forEach(function(x){try{map.removeLayer(x)}catch(e){}});layers[k]=[]})}
  function vesselIcon(t){return L.divIcon({className:'',html:'<div class="oj126-vessel-icon '+esc(t.cls)+'" title="'+esc(t.vessel)+'"><span class="arrow" style="transform:rotate('+Math.round(t.bearing)+'deg)">➤</span></div>',iconSize:[34,34],iconAnchor:[17,17],popupAnchor:[0,-18]})}
  function portIcon(){return L.divIcon({className:'',html:'<div class="oj126-port-icon"></div>',iconSize:[22,22],iconAnchor:[11,11]})}
  function renderMapLayers(){if(!map||typeof L==='undefined')return;clearLayers();var visible=filteredTrips();var portsUsed={};visible.forEach(function(t){t.path.forEach(function(p,i){portsUsed[p[0]+','+p[1]]=p});var color=t.cls==='delayed'?'#dc2626':t.cls==='enroute'?'#eab308':(t.cls==='boarding'||t.cls==='soon')?'#22c55e':'#38bdf8';var route=L.polyline(t.path,{color:color,weight:t.isConnecting?3:2,opacity:.65,dashArray:t.isConnecting?'7 7':null}).addTo(map);layers.routes.push(route);var marker=L.marker(t.pos,{icon:vesselIcon(t)}).addTo(map);marker.bindTooltip(esc(t.vessel+' • '+t.title+' • '+t.status),{direction:'top'});marker.on('click',function(){selectTrip(t.id,true)});layers.markers.push(marker);if(t.progress>0&&t.progress<1){var covered=L.polyline(t.path.slice(0,1).concat([t.pos]),{color:'#fff',weight:1,opacity:.45,dashArray:'2 6'}).addTo(map);layers.routes.push(covered)}});Object.keys(portsUsed).forEach(function(k){var p=portsUsed[k];var m=L.marker(p,{icon:portIcon()}).addTo(map);layers.ports.push(m)});if(visible.length){var group=L.featureGroup(layers.markers.concat(layers.routes));try{map.fitBounds(group.getBounds().pad(.18),{animate:false})}catch(e){}}else{focusCebu()}
    renderWeatherOverlay()}
  function initLeaflet(){var box=id('oj126LiveMap');if(!box)return;if(typeof L==='undefined'){box.innerHTML='<div class="oj126-map-fallback"><div><b>Map library is not loaded.</b><br>Timeline and vessel lists still work. Check internet connection for Leaflet tiles.</div></div>';return}if(map){try{map.remove()}catch(e){}map=null}map=L.map('oj126LiveMap',{zoomControl:true,attributionControl:false,preferCanvas:true}).setView(PORTS.cebu,8);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:18}).addTo(map);renderMapLayers();setTimeout(function(){try{map.invalidateSize(false)}catch(e){}},150)}
  function focusCebu(){if(map)map.setView(PORTS.cebu,9,{animate:false})}
  function focusTrip(idv){var t=tripCache.filter(function(x){return x.id===idv})[0]||makeTrips().filter(function(x){return x.id===idv})[0];if(t&&map){map.setView(t.pos,10,{animate:false});selectTrip(idv,false)}}
  function selectTrip(idv,skipFocus){var t=makeTrips().filter(function(x){return x.id===idv})[0];if(!t)return;selectedId=idv;var detail=id('oj126Detail');if(detail)detail.innerHTML=detailHtml(t);if(!skipFocus&&map)map.setView(t.pos,10,{animate:false})}
  function applyDelay(){var sid=id('oj126DelayTrip')?id('oj126DelayTrip').value:'';var val=Number(id('oj126DelayMin')?id('oj126DelayMin').value:0)||0;if(!sid)return;var d=delayMap();if(val<=0)delete d[sid];else d[sid]=val;saveDelays(d);toastMsg('Delay updated');refresh()}
  function resetDelays(){if(confirm('Reset all manual map delays?')){localStorage.removeItem(DELAY_KEY);toastMsg('Map delays reset');refresh()}}
  function exportCSV(){var rows=[['Date','Vessel','Route','Departure','Arrival','Status','Progress %','ETA minutes','Delay minutes','Fare Summary','Schedule Mode']];todaysTrips().forEach(function(t){rows.push([new Date().toLocaleDateString('en-PH'),t.vessel,t.title,fmtTime(t.actualDep),fmtTime(t.actualArr),t.status,t.progressPct,t.etaMin,t.delay,fareSummary(t),'Schedule-based estimated position'])});download('oceanjet_v500_vessel_manifest.csv',csv(rows),'text/csv')}
  function copyTrip(idv){var t=makeTrips().filter(function(x){return x.id===idv})[0];if(!t)return;var text='OceanJet Vessel Summary\n'+tripLine(t)+'\nStatus: '+t.status+'\nETA: '+(t.etaMin?t.etaMin+' minutes':'Arrived')+'\nFare: '+fareSummary(t)+'\nMode: Schedule-based estimated position';if(navigator.clipboard)navigator.clipboard.writeText(text);toastMsg('Vessel summary copied')}
  function askTrip(idv){var t=makeTrips().filter(function(x){return x.id===idv})[0];if(!t)return;var prompt='Summarize this OceanJet vessel for staff: '+tripLine(t)+'. Status '+t.status+', ETA '+(t.etaMin?t.etaMin+' minutes':'arrived')+'. Mention that map position is schedule-based, not GPS.';try{var panel=id('chatPanel');var input=id('chatInput');if(panel&&!panel.classList.contains('open')&&typeof toggleChat==='function')toggleChat();if(input){input.value=prompt;input.focus();toastMsg('Gemini prompt ready. Tap Send.');return}}catch(e){}if(navigator.clipboard)navigator.clipboard.writeText(prompt);toastMsg('Gemini prompt copied')}
  function refresh(){makeTrips();renderAll();if(map)renderMapLayers()}

  /* V500: Weather overlay functions */
  function weatherIconForCode(code){try{return getWeatherIcon(code)}catch(e){return '\u26c5'}}
  function seaConditionForWeather(code,wind){try{return getSeaCondition(code,wind)}catch(e){return {level:'calm',color:'#22c55e',icon:'\u26c5',advisory:'Normal conditions'}}}
  var weatherOverlayVisible=true;
  function fetchPortWeather(callback){
    var now=Date.now();
    if(weatherCache&&now-weatherLastFetch<600000){callback(weatherCache);return}
    var regions=typeof WEATHER_REGIONS!=='undefined'?WEATHER_REGIONS:[];
    if(!regions.length){callback(null);return}
    var url='https://api.open-meteo.com/v1/forecast?latitude='+regions.map(function(r){return r.lat}).join(',')+'&longitude='+regions.map(function(r){return r.lng}).join(',')+'&current=temperature_2m,weather_code,wind_speed_10m&timezone=Asia/Manila';
    fetch(url).then(function(r){return r.json()}).then(function(data){weatherCache=data;weatherLastFetch=now;callback(data)}).catch(function(){callback(null)});
  }
  function renderWeatherOverlay(){
    if(!map||!weatherOverlayVisible)return;
    layers.weather.forEach(function(x){try{map.removeLayer(x)}catch(e){}});
    layers.weather=[];
    var regions=typeof WEATHER_REGIONS!=='undefined'?WEATHER_REGIONS:[];
    if(!regions.length)return;
    fetchPortWeather(function(data){
      if(!data||!data.current)return;
      regions.forEach(function(region,i){
        var temp=data.current.temperature_2m?data.current.temperature_2m[i]:null;
        var code=data.current.weather_code?data.current.weather_code[i]:0;
        var wind=data.current.wind_speed_10m?data.current.wind_speed_10m[i]:0;
        var sea=seaConditionForWeather(code,wind);
        var color=sea.level==='calm'?'#22c55e':sea.level==='moderate'?'#eab308':'#ef4444';
        var circle=L.circleMarker([region.lat,region.lng],{radius:18,color:color,fillColor:color,fillOpacity:.15,weight:2,opacity:.6}).addTo(map);
        var tooltip='<b>'+esc(region.name)+'</b><br>'+weatherIconForCode(code)+' '+Math.round(temp||0)+'\u00b0C<br>\u26c5 '+Math.round(wind||0)+' km/h<br>Sea: '+esc(sea.level)+' '+esc(sea.advisory);
        circle.bindTooltip(tooltip,{direction:'top',className:'weather-tooltip'});
        layers.weather.push(circle);
      });
    });
  }

  window.buildMap=function(){if(refreshTimer){clearInterval(refreshTimer);refreshTimer=null}if(map){try{map.remove()}catch(e){}map=null}var root=id('view-map');if(!root)return;root.innerHTML='<div class="oj126-wrap"><div id="oj126Top">'+renderTop()+'</div>'+filtersHtml()+'<div class="oj126-grid"><div>'+mapHtml()+'</div><div id="oj126Detail">'+detailHtml(nextBoarding())+'</div></div><div id="oj126Timeline">'+timelineHtml()+'</div><div id="oj126DelayHolder">'+delayHtml()+'</div><div class="oj126-card"><div class="oj126-title"><span>🧠 Accuracy Rules</span><span class="oj126-badge">Professional mode</span></div><div class="oj126-note" style="margin-top:8px">This map calculates vessel position from schedule time, route waypoints, and manual delay overrides. It will never pretend to be true GPS. Weather overlay shows real-time conditions at each port via Open-Meteo API. Later, a real GPS/AIS or dispatch API can replace the schedule position engine.</div></div></div>';setTimeout(function(){initLeaflet();refreshTimer=setInterval(refresh,60000)},180)};
  window.initMap=function(){initLeaflet()};
  window.OJLiveMapV126={version:VERSION,setFilter:function(f){activeFilter=f;localStorage.setItem(FILTER_KEY,f);window.buildMap()},refresh:refresh,select:selectTrip,focus:focusTrip,focusNext:function(){var n=nextBoarding();if(n)focusTrip(n.id);else focusCebu()},focusCebu:focusCebu,applyDelay:applyDelay,resetDelays:resetDelays,exportCSV:exportCSV,copy:copyTrip,ask:askTrip,toggleWeather:function(){weatherOverlayVisible=!weatherOverlayVisible;if(map)renderMapLayers();toastMsg('Weather overlay '+(weatherOverlayVisible?'shown':'hidden'))}};
  function boot(){try{var item=document.querySelector('[data-view="map"]');if(item)item.innerHTML='<i>🗺️</i> Live Map Pro';}catch(e){}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
